---
title: "Report"
author: "Javier Esteban Aragoneses"
date: "6/3/2019"
output: html_document
params: 
   Namex: NA
   Namey: NA
   datos: NA
   NameHist: NA
   Namegg: NA
---
```{r include=FALSE}
library(shiny)
library(tidyverse)
library(shinyWidgets)
library(magrittr)
library(tableHTML)

```


```{r include=FALSE}

datos=params$datos

```

```{r echo=FALSE}
h=datos%>% select(params$NameHist)
h=as.vector(as.matrix(h))
hist(h,xlab =params$NameHist,main="Histrogram of the stat selected
")
```

```{r echo=FALSE}

x=datos%>% select(params$Namex)
y=datos%>% select(params$Namey)
x=as.vector(as.matrix(x))
y=as.vector(as.matrix(y))
plot(x=x,y=y,main="Plot of data player",xlab=params$Namex,ylab=params$Namey,col = "#00AFBB")
```

```{r echo=FALSE}
GG=datos%>% select(params$Namegg)
GG=as.vector(as.matrix(GG))

datos %>% ggplot(aes(x = GG)) +  
        geom_density(aes(group = Pos, 
                         colour = Pos, 
                         fill = Pos),
                     alpha = 0.2)
```


